# Generated by Django 5.0.4 on 2024-04-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='token_generated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
