# Generated by Django 5.0.4 on 2024-04-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose_of_visit_model',
            name='purpose',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='class_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('address', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.branchmodel')),
                ('crn_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_rooms', to='console.register_model')),
            ],
        ),
    ]
