# Generated by Django 5.0.4 on 2024-04-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_alter_leadmodel_token_generated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='lead_position',
            field=models.CharField(choices=[('PROSPECT', 'PROSPECT'), ('LEAD', 'LEAD'), ('ASSIGNED_DEMO', 'ASSIGNED_DEMO'), ('ATTENDED_DEMO', 'ATTENDED_DEMO'), ('REQUEST_DISCOUNT', 'REQUEST_DISCOUNT'), ('OPPORTUNITY', 'OPPORTUNITY'), ('ADMITTED', 'ADMITTED'), ('SPAM', 'SPAM')], default='PROSPECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead_generation',
            name='lead_position',
            field=models.CharField(choices=[('LEAD', 'LEAD'), ('ASSIGNED_DEMO', 'ASSIGNED_DEMO'), ('ATTENDED_DEMO', 'ATTENDED_DEMO'), ('REQUEST_DISCOUNT', 'REQUEST_DISCOUNT'), ('OPPORTUNITY', 'OPPORTUNITY'), ('ADMITTED', 'ADMITTED'), ('SPAM', 'SPAM')], max_length=100),
        ),
    ]
