# Generated by Django 5.0.4 on 2024-04-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_leadmodel_lead_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='lead_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='console.leadstage'),
        ),
    ]
