# Generated by Django 5.0.4 on 2024-04-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_lead_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobrole_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=20)),
                ('crn_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobrole', to='console.register_model')),
            ],
        ),
    ]
