# Generated by Django 5.0.4 on 2024-04-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_leadmodel_lead_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadmodel',
            old_name='lead_type',
            new_name='lead_sourse',
        ),
    ]
