# Generated by Django 5.0.4 on 2024-04-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_jobrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_model',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='register_model',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
