# Generated by Django 5.0.4 on 2024-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_alter_register_model_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='demobannerimage',
            field=models.ImageField(default=True, null=True, upload_to='demo_banner'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='demoimage',
            field=models.ImageField(default=True, null=True, upload_to='demo_image'),
        ),
    ]
