# Generated by Django 5.0.4 on 2024-04-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_rename_lead_type_leadmodel_lead_sourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='demo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='console.demo'),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='lead_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
