# Generated by Django 5.0.4 on 2024-04-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_leadmodel_demo_leadmodel_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='console.employee_model'),
        ),
    ]
