# Generated by Django 5.0.4 on 2024-04-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_alter_demo_demobannerimage_alter_demo_demoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemanage',
            name='course_banner',
            field=models.ImageField(blank=True, null=True, upload_to='course_banner'),
        ),
        migrations.AlterField(
            model_name='coursemanage',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_image'),
        ),
        migrations.AlterField(
            model_name='coursemanage',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='Curriculum'),
        ),
        migrations.AlterField(
            model_name='coursemanage',
            name='teaching_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.employee_model'),
        ),
    ]
