# Generated by Django 5.0.4 on 2024-04-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_leadmodel_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmodel',
            name='generated_From',
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='lead_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='demo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.demo'),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.employee_model'),
        ),
        migrations.AlterField(
            model_name='leadmodel',
            name='lead_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.leadstage'),
        ),
    ]
