# Generated by Django 5.0.4 on 2024-04-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_remove_leadmodel_generated_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='lead_position',
            field=models.CharField(choices=[('PROSPECT', 'PROSPECT'), ('LEAD', 'LEAD'), ('MQL', 'MQL'), ('ASSIGNED_DEMO', 'ASSIGNED_DEMO'), ('ATTENDED_DEMO', 'ATTENDED_DEMO'), ('REQUEST_DISCOUNT', 'REQUEST_DISCOUNT'), ('OPPORTUNITY', 'OPPORTUNITY'), ('ADMITTED', 'ADMITTED'), ('SPAM', 'SPAM')], default='PROSPECT', max_length=100),
        ),
    ]
