# Generated by Django 5.0.4 on 2024-04-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_alter_leadmodel_lead_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='mql_description',
            field=models.TextField(null=True),
        ),
    ]
