# Generated by Django 5.0.4 on 2024-04-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_alter_leadmodel_lead_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='lead_type',
            field=models.CharField(choices=[('WARM', 'WARM'), ('COLD', 'COLD')], max_length=100, null=True),
        ),
    ]
